version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # port exposed : mysql port running inside container
      - "33062:3306"
    expose:
      # opens port 3306 on the container
      - "33062"
    volumes: # where the data is persisted
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  my-db: